### ISSUE TITLE
Bug in flat_boolean_domain

### ISSUE THREAD

**Issue by ffrohn** [seahorn/crab#64]
[This line](https://github.com/seahorn/crab/blob/146f5399c72ff508f176e6392e490647ac657ce7/include/crab/domains/flat_boolean_domain.hpp#L402C9-L402C54) looks very suspicious. Shouldn't the inequation be the other way around? I didn't try to create an example that triggers the bug (if it is one), I just stumbled across this line when I was looking at the code to understand how Booleans are handled.

**Comment by caballa** [comment]
Hi Florian, 

Thank you for reporting this bug. 
It has been fixed in commit [4d934fe](https://github.com/seahorn/crab/commit/4d934fedac3a1ce123502d2afec8c9ee86c5a89b)
